name: Deploy Laravel App

on:
  push:
    branches: [ main ]

env:
  DOCKER_COMPOSE_VERSION: 1.29.2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
#          npm install --omit=dev
#          npm run build

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Deploy files via rsync
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='node_modules' \
          --exclude='.env' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/laravel-app

      - name: Run deployment commands
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
            cd /var/www/laravel-app
            if [ ! -f .env ]; then
              cp .env.example .env
            fi
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            docker-compose exec -T app composer install --no-dev --no-interaction
            docker-compose exec -T app php artisan key:generate --force
            docker-compose exec -T app php artisan migrate --force
            docker-compose exec -T app php artisan storage:link
            docker-compose exec -T app chown -R www-data:www-data /var/www/storage
            docker-compose exec -T app chmod -R 775 /var/www/storage
            docker-compose exec -T app php artisan optimize
          EOF
