name: Eazzy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to QA
        uses: appleboy/ssh-action@master
        with:
          username: ${{secrets.DEV_USERNAME}}
          host: ${{secrets.DEV_HOST}}
          password: ${{secrets.DEV_PASSWORD}}
          script: |
            cd /
            git clone  hhttps://github.com/blessingchirume/erpbackoffice.git
            cd erpbackoffice
            git checkout main
            docker stop retailmate-core
            docker rm retailmate-core
            docker rmi retailmate-core
            docker build -t retailmate-core .
            docker run -d -p 7272:7272 --name=retailmate-core --restart=always retailmate-core
            cd /
            rm -rf retailmate-core
